# Generated by Django on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0003_shop_allow_staff_inventory_management"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="allow_staff_sales",
            field=models.BooleanField(default=True),
        ),
    ]
