# Generated by Django on 2026-05-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0004_shop_allow_staff_sales"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="allow_staff_expense_logging",
            field=models.BooleanField(default=True),
        ),
    ]
