# Generated by Django 6.0.3 on 2026-05-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_1', models.CharField(blank=True, db_index=True, help_text='Primary IMEI (15 digits for phones)', max_length=20)),
                ('imei_2', models.CharField(blank=True, help_text='Secondary IMEI for dual-SIM devices', max_length=20)),
                ('serial_number', models.CharField(blank=True, db_index=True, help_text='Serial number (for laptops, tablets, accessories)', max_length=100)),
                ('condition', models.CharField(choices=[('new', 'New'), ('refurbished', 'Refurbished'), ('used', 'Used')], default='new', max_length=20)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('sold', 'Sold'), ('reserved', 'Reserved'), ('returned', 'Returned'), ('defective', 'Defective')], default='in_stock', max_length=20)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, help_text='Actual cost paid for this specific unit', max_digits=12, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('selling_price_actual', models.DecimalField(blank=True, decimal_places=2, help_text='Actual price this unit was sold for', max_digits=12, null=True)),
                ('warranty_months', models.PositiveIntegerField(default=0, help_text='Warranty duration in months from sale date')),
                ('color', models.CharField(blank=True, max_length=100)),
                ('storage', models.CharField(blank=True, help_text='e.g. 128GB, 256GB', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
