# Generated by Django 6.0.3 on 2026-05-11 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0004_productunit'),
        ('sales', '0006_rename_sales_salep_created_8ef013_idx_sales_salep_created_61f1e0_idx_and_more'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_received', to='suppliers.purchaseorder'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_sold', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='sold_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_purchased', to='customers.customer'),
        ),
        migrations.AddField(
            model_name='productunit',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units_supplied', to='suppliers.supplier'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product', 'status'], name='inventory_p_product_cd764a_idx'),
        ),
        migrations.AddIndex(
            model_name='productunit',
            index=models.Index(fields=['product', '-created_at'], name='inventory_p_product_a852df_idx'),
        ),
    ]
