# Generated by Django 6.0.3 on 2026-05-03 15:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salepayment'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salepayment',
            new_name='sales_salep_created_61f1e0_idx',
            old_name='sales_salep_created_8ef013_idx',
        ),
        migrations.RenameIndex(
            model_name='salepayment',
            new_name='sales_salep_sale_id_a281e6_idx',
            old_name='sales_salep_sale_id_716898_idx',
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
